// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVFNVsnpa31G5THxCs7Ef01yAZySSPsyU',
    appId: '1:718616577077:web:a47c562f623ee6cd189d7c',
    messagingSenderId: '718616577077',
    projectId: 'clinicalsystem-4da35',
    authDomain: 'clinicalsystem-4da35.firebaseapp.com',
    storageBucket: 'clinicalsystem-4da35.firebasestorage.app',
    measurementId: 'G-MGCW042T2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe3PBCeDsTGLqgxi0On9WixxyytIDTFG0',
    appId: '1:718616577077:android:a89d1cd590e78406189d7c',
    messagingSenderId: '718616577077',
    projectId: 'clinicalsystem-4da35',
    storageBucket: 'clinicalsystem-4da35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLdZ6S-VUwar2Oi-CPNaEobc1LvKb8xA0',
    appId: '1:718616577077:ios:2da3350695fb985c189d7c',
    messagingSenderId: '718616577077',
    projectId: 'clinicalsystem-4da35',
    storageBucket: 'clinicalsystem-4da35.firebasestorage.app',
    iosBundleId: 'com.mored.mallawycare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLdZ6S-VUwar2Oi-CPNaEobc1LvKb8xA0',
    appId: '1:718616577077:ios:dc5fe68a823452fc189d7c',
    messagingSenderId: '718616577077',
    projectId: 'clinicalsystem-4da35',
    storageBucket: 'clinicalsystem-4da35.firebasestorage.app',
    iosBundleId: 'com.example.clinicalsystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVFNVsnpa31G5THxCs7Ef01yAZySSPsyU',
    appId: '1:718616577077:web:b547cbf73d596663189d7c',
    messagingSenderId: '718616577077',
    projectId: 'clinicalsystem-4da35',
    authDomain: 'clinicalsystem-4da35.firebaseapp.com',
    storageBucket: 'clinicalsystem-4da35.firebasestorage.app',
    measurementId: 'G-S7BG307B3J',
  );
}
